spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/paymentdb}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
value.from.file=Value annotation
priority=high
listOfValues=A,B,C